version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: money-transfer-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-money_transfer}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-money_transfer}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U money_transfer"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local